# docker build -t fer-api:latest . -f ci\Dockerfile


# Dockerfile
FROM --platform=$BUILDPLATFORM tensorflow/tensorflow:2.10.0 AS builder

WORKDIR /app

COPY ./requirements.txt ${WORKDIR}
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install Flask==2.2.3 numpy==1.24.1 opencv-python-headless

COPY src ${WORKDIR}

# Expose the port that Flask will run on
EXPOSE 5000

CMD ["flask", "--app", "app.py", "run", "--host=0.0.0.0", "--port=5000"]